
apiVersion: v1
kind: ConfigMap
metadata:
  name: wfm-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
